name: Lint Code

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install flake8
      run: |
        pip install flake8

    - name: Run flake8
      run: |
        flake8 wumpus.py test_wumpus.py
